<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbad9c7d347348dddeaba25608b280c5e
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Liste_de_course\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Liste_de_course\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbad9c7d347348dddeaba25608b280c5e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbad9c7d347348dddeaba25608b280c5e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbad9c7d347348dddeaba25608b280c5e::$classMap;

        }, null, ClassLoader::class);
    }
}
